- name: Uninstall old versions
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Download GPG key
  ansible.builtin.copy:
    content: >-
      {{ lookup(
        'ansible.builtin.url',
        docker_apt_repository.gpg_key.url,
        split_lines=False)
      }}
    dest: "{{ docker_apt_repository.gpg_key.path }}.ascii"
    mode: "0644"
  notify: Dearmor GPG key
- name: Flush handlers
  ansible.builtin.meta: flush_handlers
- name: Add APT repository
  ansible.builtin.apt_repository:
    repo: "{{ docker_apt_repository_entry }}"
    state: present
- name: Install
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
