- name: Dearmor GPG key
  ansible.builtin.command: >-
    gpg
    --batch --yes
    --dearmor
    -o {{ docker_apt_repository.gpg_key.path }}
    {{ docker_apt_repository.gpg_key.path }}.ascii
  changed_when: true # only triggered when the ASCII key changed
- name: Reload Systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Restart Docker service
  ansible.builtin.service:
    name: docker
    state: restarted
- name: Reload Docker service
  ansible.builtin.service:
    name: docker
    state: reloaded
