docker_apt_repository_entry: >-
  deb
  [arch={{ docker_apt_repository.arch }}
  signed-by={{ docker_apt_repository.gpg_key.path }}]
  {{ docker_apt_repository.url }}
  {{ docker_apt_repository.distribution }}
  {{ docker_apt_repository.components }}
docker_tcp_port: "{{ lookup('ansible.builtin.pipe', 'op read \"op://IaC/Docker SSL server certificate - Kenny/port\"') }}"
